{% set name = "python-lzo" %}
{% set version = "1.12" %}
{% set sha256 = "97a8e46825e8f1abd84c2a3372bc09adae9745a5be5d3af2692cd850dac35345" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win]
  number: 1000

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - lzo 2.10.*
  run:
    - python
    - lzo 2.10.*

test:
  imports:
    - lzo

about:
  home: https://github.com/jd-boyd/python-lzo
  license: GPL-2.0
  license_file: COPYING
  summary: 'Python bindings for the LZO data compression library'
  description: |
    Python-LZO provides Python bindings for LZO, i.e. you can access
    the LZO library from your Python scripts thereby compressing
    ordinary Python strings.

extra:
  recipe-maintainers:
    - sebastian-luna-valero
